services:

    web:
        build: .
        volumes:
            - ./:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./.env.dev
        depends_on:
            - db

    db:
        image: postgres:16
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=sge_mt
            - POSTGRES_PASSWORD=masterkey
            - POSTGRES_DB=sge_mt_dev

volumes:
    postgres_data:
